### ISSUE TITLE
README - Presumed error

### ISSUE THREAD

**Issue by aldovincenti** [hansott/psr7-cookies#2]
![schermata 2018-08-22 alle 21 12 28](https://user-images.githubusercontent.com/22561502/44485233-429d4e00-a650-11e8-85ca-67bac763c24f.png)

Maybe it should be `$cookies`.

**Comment by hansott** [comment]
Oh, boy, that doesn't look right 😬 Thanks for reporting.

**Comment by hansott** [comment]
@aldovincenti May I ask why you went for https://github.com/aldovincenti/AntiCsrfMiddleware/blob/master/composer.json#L16 instead of this library? Perhaps I can improve my library. Thanks in advance!

**Comment by aldovincenti** [comment]
@hansott I'm about to release a new version with you library :)
