### ISSUE TITLE
Force cast cookie name to string

### ISSUE THREAD

**Issue by spotman** [hansott/psr7-cookies#3]
Hello!

First of all, I want to say thank you for your library! I'm using it on top of zend-expressive and someone is trying to hack the website by sending wrong request data (integer cookie name). So I see this error in logs:

```
[0] TypeError: Argument 1 passed to HansOtt\PSR7Cookies\Cookie::__construct() must be of the type string, integer given, called in vendor/hansott/psr7-cookies/src/RequestCookies.php
```

Is it possible to cast cookie name to `string` before creating `Cookie` instance?

**Comment by hansott** [comment]
Hi! I'll get back to you later today. 😊

**Comment by hansott** [comment]
Thanks for reporting! I was able to reproduce. I've tagged a new version: https://github.com/hansott/psr7-cookies/releases/tag/2.0.1

**Comment by spotman** [comment]
Thank you, Hans! I'll check it shortly.
