### ISSUE TITLE
Removing cookie(s)

### ISSUE THREAD

**Issue by wannfq** [hansott/psr7-cookies#8]
Hey! Thank you for the awesome package. 
Some questions;
- Is there any way I could remove a cookie with this package?
- (If not) Would you implement a method to remove a cookie?

**Comment by hansott** [comment]
Howdy @wannfq, sorry for the late reply (I was on holiday). This is documented in the readme:

```php
$cookie = SetCookie::thatDeletesCookie('name');
$responseWithoutCookie = $cookie->addToResponse($response);
```

Let me know if that works for you!

**Comment by wannfq** [comment]
Thank you for responding. Your solution works for me.
Wouldn't it be better if we just set the value as an empty string instead of `deleted` here?
 [https://github.com/hansott/psr7-cookies/blob/0bf2f5d48cec1d7deb9b7b9bc37b70b4c1e5aaab/src/SetCookie.php#L64](url)

**Comment by hansott** [comment]
I can't recall why I used `deleted` 😬 ... Symfony also uses `deleted`: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Cookie.php#L147 I'm not sure whether an empty string is better... 🤔

**Comment by wannfq** [comment]
Nice job on pointing that out! I guess using `deleted` seems more reasonable since it's better to establish consistency between different resources.
