### ISSUE TITLE
expires date format

### ISSUE THREAD

**Issue by pine3ree** [hansott/psr7-cookies#9]
Hello, 

1. According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date the date format whould be 
`'D, d M Y H:i:s T'` instead of 
`'D, d-M-Y H:i:s T'`
I have seen (and used) both the formats, but I tend to follow MDN specs.

2. Should we also be able to set the expiration dat using a cookie ttl/lifetime value instead of the actual expiry date/timestamp, so that both `Expires` and `Max-Age` can be added to the header?
(btw, calculating Max-Age from timestamp would not be good as we would have to subtract current `time()` that in the (`toHeaderValue`)-call could accidentally yield an extra second since it was set) . Maybe a simple `thatExpiresIn()` method.

kind regards,
maks

**Comment by hansott** [comment]
Hey Maks!

1. I was inspired by Symfony's `Cookie`: https://github.com/symfony/symfony/blob/34e86761f4a34c5c31ff2299bf38f1ba79709235/src/Symfony/Component/HttpFoundation/Cookie.php#L152... Looks like you're right about that. I'm happy to accept a PR. I haven't received issues about the format but I agree that it is better to follow the specs.

2. `thatExpiresIn` sounds like a good idea to me! I'm also happy to accept a PR for that part. 

I'm quite busy at this moment and it will take a while before I can tackle this. If you're up for it, I'm happy to review any PRs related to your issue. Otherwise, you can look at different libs (e.g. https://github.com/dflydev/dflydev-fig-cookies). 

Hans

**Comment by pine3ree** [comment]
Hello @hansott ,

I used dflydev-fig-cookies in zend-expressive-session-ext. I used a constant for the date format as I did for he zend package.

About point 2:
- I think it will also be good to add - for more clarity in the nomenclature - `thatExpiresAt` method as an alias for `thatExpires`, maybe deprecating this last one in a future version would be better
kind regards, 
maks

PS
I'll close the issue, since it is not an issue but a feature request...I may reference it in my PRs.

**Comment by pine3ree** [comment]
@hansott 
I have another PR (https://github.com/pine3ree/psr7-cookies/tree/that-expires-in-at) ready which:
- adds `thatExpiresIn` method (+ optional maxAge prop)
- adds `thatExpiresAt` alias method (actually substitutes thatExpires and makes it an alias)
- adds type checking in static methods (same as the ctor)
- adds several tests
- modifies the valid name tests for cookies using MDN recommendations and using a class constant

PS
I reopened the issue...I missed the "help-wanted" tag... :-).

**Comment by hansott** [comment]
@pine3ree Looks good already! Thanks for your effort! 😍

**Comment by pine3ree** [comment]
@hansott no problem, I'll wait for the 1st PR to be pulled before opening the 2nd since it's based on the first. kind regards.

**Comment by pine3ree** [comment]
Hello @hansott,

As anticipated I divided the 2nd PR into 3 different PRs based on the topic...in incremental order each one based on previous commit.
1. https://github.com/pine3ree/psr7-cookies/tree/http-date-format (currently opened and modified removing the previously added constant)
2. https://github.com/pine3ree/psr7-cookies/tree/add-type-hinting
3. https://github.com/pine3ree/psr7-cookies/tree/that-expires-at-in
4. https://github.com/pine3ree/psr7-cookies/tree/add-optional-max-age

I have another couple of suggestions but I will discuss that later.
kind regards,
maks
